version: '3'
networks:
  moph-network:
    driver: bridge
services:
  hospital-db:
    image: mariadb
    container_name: hospital-db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: hospital
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "6001:3306"
    volumes:
      - hospital-dbdata:/var/lib/mysql
      - hospital-dblog:/var/log/mysql
      - ./hospital/config/my.conf:/etc/mysql/conf.d/config-file.cnf
      - ./hospital/init:/docker-entrypoint-initdb.d
    networks:
      - moph-network
  hospital:
    container_name: hospital
    ports:
      - "3001:80"
    build:
      context: ./hospital
      dockerfile: Dockerfile
    depends_on:
      - hospital-db
    volumes:
      - ./hospital:/usr/src/app
    networks:
      - moph-network
  hospital-pipeline:
    container_name: hospital-pipeline
    ports:
      - "3002:80"
    build:
      context: ./hospital-pipeline
      dockerfile: Dockerfile
    depends_on:
      - hospital-db
    volumes:
      - ./hospital-pipeline:/usr/src/app
    networks:
      - moph-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"
    networks:
      - moph-network
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - 8800:8000
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  kong-database:
    image: postgres:13
    container_name: kong-database
    networks:
      - moph-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    volumes:
      - kong_data:/var/lib/postgresql/data
  kong-migrations:
    image: kong:3.7.0
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
    depends_on:
      - kong-database
    networks:
      - moph-network
  kong:
    image: kong:3.7.0
    networks:
      - moph-network
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - 8000:8000
      - 8443:8443
      - 127.0.0.1:8001:8001
      - 127.0.0.1:8002:8002
      - 127.0.0.1:8444:8444
volumes:
  hospital-dbdata: {}
  hospital-dblog: {}
  portainer_data: {}
  kong_data: {}